package com.icss.oa.meeting.pojo;
import java.sql.Timestamp;

public class Meeting {
	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column MEETING.MEET_ID
	     *
	     * @mbggenerated Thu Jul 02 13:46:42 CST 2015
	     */
	    private Integer meetId;
	    
	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column MEETING.MEET_DATE
	     *
	     * @mbggenerated Thu Jul 02 13:46:42 CST 2015
	     */
	    private Timestamp meetDateBegin;
	    private Timestamp meetDateEnd;
	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column MEETING.ROOM_ID
	     *
	     * @mbggenerated Thu Jul 02 13:46:42 CST 2015
	     */
	    private Integer roomId;
	    private Integer meetState;
	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column MEETING.ORIGINATOR
	     *
	     * @mbggenerated Thu Jul 02 13:46:42 CST 2015
	     */
	    private Integer originator;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column MEETING.THEME
	     *
	     * @mbggenerated Thu Jul 02 13:46:42 CST 2015
	     */
	    private String theme;

	    

		public Meeting(Integer meetId, Timestamp meetDateBegin,
				 Integer roomId, Integer originator,
				String theme,Timestamp meetDateEnd,Integer meetState) {
			super();
			this.meetId = meetId;
			this.meetDateBegin = meetDateBegin;
			this.meetDateEnd = meetDateEnd;
			this.roomId = roomId;
			this.originator = originator;
			this.theme = theme;
			this.meetState=meetState;
		}

		public Meeting(Timestamp meetDateBegin,
				 Integer roomId, Integer originator,
				String theme,Timestamp meetDateEnd,Integer meetState) {
			super();
			this.meetDateBegin = meetDateBegin;
			this.meetDateEnd = meetDateEnd;
			this.roomId = roomId;
			this.originator = originator;
			this.theme = theme;
			this.meetState=meetState;
		}

		public Meeting() {

			// TODO Auto-generated constructor stub
		}
		
		public Integer getMeetId() {
			return meetId;
		}

		public void setMeetId(Integer meetId) {
			this.meetId = meetId;
		}

		public Timestamp getMeetDateBegin() {
			return meetDateBegin;
		}

		public void setMeetDateBegin(Timestamp meetDateBegin) {
			this.meetDateBegin = meetDateBegin;
		}

		public Timestamp getMeetDateEnd() {
			return meetDateEnd;
		}

		public void setMeetDateEnd(Timestamp meetDateEnd) {
			this.meetDateEnd = meetDateEnd;
		}

		public Integer getRoomId() {
			return roomId;
		}

		public void setRoomId(Integer roomId) {
			this.roomId = roomId;
		}

		public Integer getMeetState() {
			return meetState;
		}

		public void setMeetState(Integer meetState) {
			this.meetState = meetState;
		}

		public Integer getOriginator() {
			return originator;
		}

		public void setOriginator(Integer originator) {
			this.originator = originator;
		}

		public String getTheme() {
			return theme;
		}

		public void setTheme(String theme) {
			this.theme = theme;
		}

		@Override
		public String toString() {
			return "Meeting [meetId=" + meetId + ", meetDateBegin="
					+ meetDateBegin + ", meetDateEnd=" + meetDateEnd
					+ ", roomId=" + roomId + ", meetState=" + meetState
					+ ", originator=" + originator + ", theme=" + theme + "]";
		}
	    
	}

