package com.icss.oa.record.pojo;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RECORD.REC_ID
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    private Integer recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RECORD.MEET_ID
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    private Integer meetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RECORD.REC_HTML
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    private byte[] recHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECORD.REC_ID
     *
     * @return the value of RECORD.REC_ID
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECORD.REC_ID
     *
     * @param recId the value for RECORD.REC_ID
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECORD.MEET_ID
     *
     * @return the value of RECORD.MEET_ID
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    public Integer getMeetId() {
        return meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECORD.MEET_ID
     *
     * @param meetId the value for RECORD.MEET_ID
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    public void setMeetId(Integer meetId) {
        this.meetId = meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECORD.REC_HTML
     *
     * @return the value of RECORD.REC_HTML
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    public byte[] getRecHtml() {
        return recHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECORD.REC_HTML
     *
     * @param recHtml the value for RECORD.REC_HTML
     *
     * @mbggenerated Mon Jul 20 16:24:28 CST 2015
     */
    public void setRecHtml(byte[] recHtml) {
        this.recHtml = recHtml;
    }

	public Record() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Record(Integer recId, Integer meetId, byte[] recHtml) {
		super();
		this.recId = recId;
		this.meetId = meetId;
		this.recHtml = recHtml;
	}

	@Override
	public String toString() {
		return "Record [recId=" + recId + ", meetId=" + meetId;
	}
	
	
    
}