package com.icss.oa.work.pojo;

public class Agent {
    public Agent() {
		super();
	}

	public Agent(Integer empId, Integer managerId, Integer agent) {
		super();
		this.empId = empId;
		this.managerId = managerId;
		this.agent = agent;
	}

	public Agent(Integer uaId, Integer empId, Integer managerId, 
			Integer agent) {
		super();
		this.uaId = uaId;
		this.empId = empId;
		this.managerId = managerId;
		this.agent = agent;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.UA_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    private Integer uaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.EMP_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.MANAGER_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.READ
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
   
    private Integer agent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.UA_ID
     *
     * @return the value of AGENT.UA_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public Integer getUaId() {
        return uaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.UA_ID
     *
     * @param uaId the value for AGENT.UA_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public void setUaId(Integer uaId) {
        this.uaId = uaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.EMP_ID
     *
     * @return the value of AGENT.EMP_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.EMP_ID
     *
     * @param empId the value for AGENT.EMP_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.MANAGER_ID
     *
     * @return the value of AGENT.MANAGER_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.MANAGER_ID
     *
     * @param managerId the value for AGENT.MANAGER_ID
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.AGENT
     *
     * @return the value of AGENT.AGENT
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public Integer getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.AGENT
     *
     * @param agent the value for AGENT.AGENT
     *
     * @mbggenerated Thu Jul 02 13:17:41 CST 2015
     */
    public void setAgent(Integer agent) {
        this.agent = agent;
    }
}