package com.icss.oa.work.pojo;

public class TaskList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_LIST.UT_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    private Integer utId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_LIST.EMP_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_LIST.MANAGER_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_LIST.TASK_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    private Integer taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_LIST.UT_ID
     *
     * @return the value of TASK_LIST.UT_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public Integer getUtId() {
        return utId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_LIST.UT_ID
     *
     * @param utId the value for TASK_LIST.UT_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public void setUtId(Integer utId) {
        this.utId = utId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_LIST.EMP_ID
     *
     * @return the value of TASK_LIST.EMP_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_LIST.EMP_ID
     *
     * @param empId the value for TASK_LIST.EMP_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_LIST.MANAGER_ID
     *
     * @return the value of TASK_LIST.MANAGER_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_LIST.MANAGER_ID
     *
     * @param managerId the value for TASK_LIST.MANAGER_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_LIST.TASK_ID
     *
     * @return the value of TASK_LIST.TASK_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_LIST.TASK_ID
     *
     * @param taskId the value for TASK_LIST.TASK_ID
     *
     * @mbggenerated Tue Jun 30 15:40:35 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

	public TaskList(Integer empId, Integer managerId, Integer taskId) {
		super();
		this.empId = empId;
		this.managerId = managerId;
		this.taskId = taskId;
	}

	public TaskList() {
		super();
	}

	public TaskList(Integer utId, Integer empId, Integer managerId,
			Integer taskId) {
		super();
		this.utId = utId;
		this.empId = empId;
		this.managerId = managerId;
		this.taskId = taskId;
	}
}