package com.icss.oa.work.pojo;

import java.util.Date;

public class Task {
    public Task(Integer taskId, String taskName, String taskContent,
			Date taskDate, Integer state, Date startTime, Date finishTime) {
		super();
		this.taskId = taskId;
		this.taskName = taskName;
		this.taskContent = taskContent;
		this.taskDate = taskDate;
		this.state = state;
		this.startTime = startTime;
		this.finishTime = finishTime;
	}

	public Task(String taskName, String taskContent, Date taskDate,
			Integer state, Date startTime, Date finishTime) {
		super();
		this.taskName = taskName;
		this.taskContent = taskContent;
		this.taskDate = taskDate;
		this.state = state;
		this.startTime = startTime;
		this.finishTime = finishTime;
	}

	public Task() {
		super();
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.TASK_ID
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.TASK_NAME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.TASK_CONTENT
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    private String taskContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.TASK_DATE
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    private Date taskDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.STATE
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.START_TIME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.FINISH_TIME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    private Date finishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.TASK_ID
     *
     * @return the value of TASK.TASK_ID
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.TASK_ID
     *
     * @param taskId the value for TASK.TASK_ID
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.TASK_NAME
     *
     * @return the value of TASK.TASK_NAME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.TASK_NAME
     *
     * @param taskName the value for TASK.TASK_NAME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.TASK_CONTENT
     *
     * @return the value of TASK.TASK_CONTENT
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public String getTaskContent() {
        return taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.TASK_CONTENT
     *
     * @param taskContent the value for TASK.TASK_CONTENT
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent == null ? null : taskContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.TASK_DATE
     *
     * @return the value of TASK.TASK_DATE
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public Date getTaskDate() {
        return taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.TASK_DATE
     *
     * @param taskDate the value for TASK.TASK_DATE
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public void setTaskDate(Date taskDate) {
        this.taskDate = taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.STATE
     *
     * @return the value of TASK.STATE
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.STATE
     *
     * @param state the value for TASK.STATE
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.START_TIME
     *
     * @return the value of TASK.START_TIME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.START_TIME
     *
     * @param startTime the value for TASK.START_TIME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.FINISH_TIME
     *
     * @return the value of TASK.FINISH_TIME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.FINISH_TIME
     *
     * @param finishTime the value for TASK.FINISH_TIME
     *
     * @mbggenerated Tue Jun 30 19:02:36 CST 2015
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
}