package com.icss.oa.carapply.pojo;

import java.util.Date;

public class CarApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.CARAPPLY_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer carapplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.EMP_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.APPLY_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.REASON
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.START_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.END_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.LEADER_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.EMP_NAME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.LEADER_NAME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private String leaderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.STATUS
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.ENDSTATUS
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer endstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_APPLY.ROUTE
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private String route;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.CARAPPLY_ID
     *
     * @return the value of CAR_APPLY.CARAPPLY_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getCarapplyId() {
        return carapplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.CARAPPLY_ID
     *
     * @param carapplyId the value for CAR_APPLY.CARAPPLY_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setCarapplyId(Integer carapplyId) {
        this.carapplyId = carapplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.EMP_ID
     *
     * @return the value of CAR_APPLY.EMP_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.EMP_ID
     *
     * @param empId the value for CAR_APPLY.EMP_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.APPLY_TIME
     *
     * @return the value of CAR_APPLY.APPLY_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.APPLY_TIME
     *
     * @param applyTime the value for CAR_APPLY.APPLY_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.REASON
     *
     * @return the value of CAR_APPLY.REASON
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.REASON
     *
     * @param reason the value for CAR_APPLY.REASON
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.START_TIME
     *
     * @return the value of CAR_APPLY.START_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.START_TIME
     *
     * @param startTime the value for CAR_APPLY.START_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.END_TIME
     *
     * @return the value of CAR_APPLY.END_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.END_TIME
     *
     * @param endTime the value for CAR_APPLY.END_TIME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.LEADER_ID
     *
     * @return the value of CAR_APPLY.LEADER_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.LEADER_ID
     *
     * @param leaderId the value for CAR_APPLY.LEADER_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.EMP_NAME
     *
     * @return the value of CAR_APPLY.EMP_NAME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.EMP_NAME
     *
     * @param empName the value for CAR_APPLY.EMP_NAME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.LEADER_NAME
     *
     * @return the value of CAR_APPLY.LEADER_NAME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.LEADER_NAME
     *
     * @param leaderName the value for CAR_APPLY.LEADER_NAME
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName == null ? null : leaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.STATUS
     *
     * @return the value of CAR_APPLY.STATUS
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.STATUS
     *
     * @param status the value for CAR_APPLY.STATUS
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.ENDSTATUS
     *
     * @return the value of CAR_APPLY.ENDSTATUS
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getEndstatus() {
        return endstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.ENDSTATUS
     *
     * @param endstatus the value for CAR_APPLY.ENDSTATUS
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setEndstatus(Integer endstatus) {
        this.endstatus = endstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_APPLY.ROUTE
     *
     * @return the value of CAR_APPLY.ROUTE
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_APPLY.ROUTE
     *
     * @param route the value for CAR_APPLY.ROUTE
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

	public CarApply(Integer carapplyId, Integer empId, Date applyTime,
			String reason, Date startTime, Date endTime, Integer leaderId,
			String empName, String leaderName, Integer status, Integer endstatus,
			String route) {
		super();
		this.carapplyId = carapplyId;
		this.empId = empId;
		this.applyTime = applyTime;
		this.reason = reason;
		this.startTime = startTime;
		this.endTime = endTime;
		this.leaderId = leaderId;
		this.empName = empName;
		this.leaderName = leaderName;
		this.status = status;
		this.endstatus = endstatus;
		this.route = route;
	}

	public CarApply() {
		super();
	}

	@Override
	public String toString() {
		return "CarApply [carapplyId=" + carapplyId + ", empId=" + empId
				+ ", applyTime=" + applyTime + ", reason=" + reason
				+ ", startTime=" + startTime + ", endTime=" + endTime
				+ ", leaderId=" + leaderId + ", empName=" + empName
				+ ", leaderName=" + leaderName + ", status=" + status
				+ ", endstatus=" + endstatus + ", route=" + route + "]";
	}
    
    
}