package com.icss.oa.carapply.pojo;
import java.util.Date;

public class CarRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_RECORD.CARRECORD_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer carrecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_RECORD.CARAPPLY_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer carapplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_RECORD.CAR_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_RECORD.DRIVER_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_RECORD.ROUTE
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private String route;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_RECORD.CARRECORD_ID
     *
     * @return the value of CAR_RECORD.CARRECORD_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private String empName;
    
    private Integer empId;
    

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public Integer getEmpId() {
		return empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public Integer getCarrecordId() {
        return carrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_RECORD.CARRECORD_ID
     *
     * @param carrecordId the value for CAR_RECORD.CARRECORD_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setCarrecordId(Integer carrecordId) {
        this.carrecordId = carrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_RECORD.CARAPPLY_ID
     *
     * @return the value of CAR_RECORD.CARAPPLY_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getCarapplyId() {
        return carapplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_RECORD.CARAPPLY_ID
     *
     * @param carapplyId the value for CAR_RECORD.CARAPPLY_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setCarapplyId(Integer carapplyId) {
        this.carapplyId = carapplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_RECORD.CAR_ID
     *
     * @return the value of CAR_RECORD.CAR_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_RECORD.CAR_ID
     *
     * @param carId the value for CAR_RECORD.CAR_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_RECORD.DRIVER_ID
     *
     * @return the value of CAR_RECORD.DRIVER_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_RECORD.DRIVER_ID
     *
     * @param driverId the value for CAR_RECORD.DRIVER_ID
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_RECORD.ROUTE
     *
     * @return the value of CAR_RECORD.ROUTE
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR_RECORD.ROUTE
     *
     * @param route the value for CAR_RECORD.ROUTE
     *
     * @mbggenerated Fri Jul 24 11:11:31 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR_RECORD.END_TIME
     *
     * @mbggenerated Mon Jul 27 22:23:52 CST 2015
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR_RECORD.CARRECORD_ID
     *
     * @return the value of CAR_RECORD.CARRECORD_ID
     *
     * @mbggenerated Mon Jul 27 22:23:52 CST 2015
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}    
    public CarRecord(Integer carrecordId, Integer carapplyId, Integer carId,
			Integer driverId, String route, String empName, Integer empId,
			Date startTime, Date endTime) {
		super();
		this.carrecordId = carrecordId;
		this.carapplyId = carapplyId;
		this.carId = carId;
		this.driverId = driverId;
		this.route = route;
		this.empName = empName;
		this.empId = empId;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public CarRecord() {
		super();
	}

	@Override
	public String toString() {
		return "CarRecord [carrecordId=" + carrecordId + ", carapplyId="
				+ carapplyId + ", carId=" + carId + ", driverId=" + driverId
				+ ", route=" + route + ", empName=" + empName + ", empId="
				+ empId + ", startTime=" + startTime + ", endTime=" + endTime
				+ "]";
	}
 
}