package com.icss.oa.folder.pojo;

public class Files {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_ID
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_NAME
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_FOLDER
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    private Integer fileFolder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_SIZE
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_CONTENT
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    private byte[] fileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_ID
     *
     * @return the value of FILES.FILE_ID
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_ID
     *
     * @param fileId the value for FILES.FILE_ID
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_NAME
     *
     * @return the value of FILES.FILE_NAME
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_NAME
     *
     * @param fileName the value for FILES.FILE_NAME
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_FOLDER
     *
     * @return the value of FILES.FILE_FOLDER
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public Integer getFileFolder() {
        return fileFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_FOLDER
     *
     * @param fileFolder the value for FILES.FILE_FOLDER
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public void setFileFolder(Integer fileFolder) {
        this.fileFolder = fileFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_SIZE
     *
     * @return the value of FILES.FILE_SIZE
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_SIZE
     *
     * @param fileSize the value for FILES.FILE_SIZE
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_CONTENT
     *
     * @return the value of FILES.FILE_CONTENT
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public byte[] getFileContent() {
        return fileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_CONTENT
     *
     * @param fileContent the value for FILES.FILE_CONTENT
     *
     * @mbggenerated Mon Jul 13 10:11:41 CST 2015
     */
    public void setFileContent(byte[] fileContent) {
        this.fileContent = fileContent;
    }
}