package com.icss.oa.folder.pojo;

public class Folder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_ID
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private Integer folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_NAME
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private String folderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_SIZE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private Long folderSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_DESCRIPTION
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private String folderDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_SHARE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private Integer folderShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_PARENT
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private Integer folderParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.EMP_ID
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.FOLDER_LEFT_SIZE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private Long folderLeftSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.CAN_DELETE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    private Integer canDelete;

    public Folder(Integer folderId, String folderName, Long folderSize,
			String folderDescription, Integer folderShare,
			Integer folderParent, Integer empId, Long folderLeftSize,
			Integer canDelete) {
		this.folderId = folderId;
		this.folderName = folderName;
		this.folderSize = folderSize;
		this.folderDescription = folderDescription;
		this.folderShare = folderShare;
		this.folderParent = folderParent;
		this.empId = empId;
		this.folderLeftSize = folderLeftSize;
		this.canDelete = canDelete;
	}

    
	public Folder() {
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_ID
     *
     * @return the value of FOLDER.FOLDER_ID
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public Integer getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_ID
     *
     * @param folderId the value for FOLDER.FOLDER_ID
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_NAME
     *
     * @return the value of FOLDER.FOLDER_NAME
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_NAME
     *
     * @param folderName the value for FOLDER.FOLDER_NAME
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setFolderName(String folderName) {
        this.folderName = folderName == null ? null : folderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_SIZE
     *
     * @return the value of FOLDER.FOLDER_SIZE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public Long getFolderSize() {
        return folderSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_SIZE
     *
     * @param folderSize the value for FOLDER.FOLDER_SIZE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setFolderSize(Long folderSize) {
        this.folderSize = folderSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_DESCRIPTION
     *
     * @return the value of FOLDER.FOLDER_DESCRIPTION
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public String getFolderDescription() {
        return folderDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_DESCRIPTION
     *
     * @param folderDescription the value for FOLDER.FOLDER_DESCRIPTION
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setFolderDescription(String folderDescription) {
        this.folderDescription = folderDescription == null ? null : folderDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_SHARE
     *
     * @return the value of FOLDER.FOLDER_SHARE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public Integer getFolderShare() {
        return folderShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_SHARE
     *
     * @param folderShare the value for FOLDER.FOLDER_SHARE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setFolderShare(Integer folderShare) {
        this.folderShare = folderShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_PARENT
     *
     * @return the value of FOLDER.FOLDER_PARENT
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public Integer getFolderParent() {
        return folderParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_PARENT
     *
     * @param folderParent the value for FOLDER.FOLDER_PARENT
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setFolderParent(Integer folderParent) {
        this.folderParent = folderParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.EMP_ID
     *
     * @return the value of FOLDER.EMP_ID
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.EMP_ID
     *
     * @param empId the value for FOLDER.EMP_ID
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.FOLDER_LEFT_SIZE
     *
     * @return the value of FOLDER.FOLDER_LEFT_SIZE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public Long getFolderLeftSize() {
        return folderLeftSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.FOLDER_LEFT_SIZE
     *
     * @param folderLeftSize the value for FOLDER.FOLDER_LEFT_SIZE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setFolderLeftSize(Long folderLeftSize) {
        this.folderLeftSize = folderLeftSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.CAN_DELETE
     *
     * @return the value of FOLDER.CAN_DELETE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public Integer getCanDelete() {
        return canDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.CAN_DELETE
     *
     * @param canDelete the value for FOLDER.CAN_DELETE
     *
     * @mbggenerated Mon Jul 13 09:55:35 CST 2015
     */
    public void setCanDelete(Integer canDelete) {
        this.canDelete = canDelete;
    }
}