package com.icss.oa.system.pojo;

public class Department {
    public Department(String deptName, String deptInfo) {
		this.deptName = deptName;
		this.deptInfo = deptInfo;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPT_ID
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPT_NAME
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPT_INFO
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    private String deptInfo;

    public Department(Integer deptId, String deptName, String deptInfo) {
		this.deptId = deptId;
		this.deptName = deptName;
		this.deptInfo = deptInfo;
	}

	public Department() {
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPT_ID
     *
     * @return the value of DEPARTMENT.DEPT_ID
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPT_ID
     *
     * @param deptId the value for DEPARTMENT.DEPT_ID
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPT_NAME
     *
     * @return the value of DEPARTMENT.DEPT_NAME
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPT_NAME
     *
     * @param deptName the value for DEPARTMENT.DEPT_NAME
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPT_INFO
     *
     * @return the value of DEPARTMENT.DEPT_INFO
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    public String getDeptInfo() {
        return deptInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPT_INFO
     *
     * @param deptInfo the value for DEPARTMENT.DEPT_INFO
     *
     * @mbggenerated Mon Jun 29 16:40:55 CST 2015
     */
    public void setDeptInfo(String deptInfo) {
        this.deptInfo = deptInfo == null ? null : deptInfo.trim();
    }
}