package com.icss.oa.system.pojo;

import java.sql.Date;


public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.EMP_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.EMP_NAME
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.EMP_NUM
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private String empNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.PASSWORD
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.GENDER
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.BIRTHDAY
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.DEPARTMENT_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.POSITION_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.PHONE
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.EMAIL
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.QQ
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.INTRODUCTION
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.EMP_ID
     *
     * @return the value of EMPLOYEE.EMP_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    public Employee() {
	}

	public Employee(String empName, String empNum, String password,
			Integer gender, Date birthday, Integer departmentId,
			Integer positionId, String phone, String email, String qq,
			String introduction) {
		this.empName = empName;
		this.empNum = empNum;
		this.password = password;
		this.gender = gender;
		this.birthday = birthday;
		this.departmentId = departmentId;
		this.positionId = positionId;
		this.phone = phone;
		this.email = email;
		this.qq = qq;
		this.introduction = introduction;
	}

	public Employee(Integer empId, String empName, String empNum,
			String password, Integer gender, Date birthday, Integer departmentId,
			Integer positionId, String phone, String email, String qq,
			String introduction) {
		this.empId = empId;
		this.empName = empName;
		this.empNum = empNum;
		this.password = password;
		this.gender = gender;
		this.birthday = birthday;
		this.departmentId = departmentId;
		this.positionId = positionId;
		this.phone = phone;
		this.email = email;
		this.qq = qq;
		this.introduction = introduction;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.EMP_ID
     *
     * @param empId the value for EMPLOYEE.EMP_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.EMP_NAME
     *
     * @return the value of EMPLOYEE.EMP_NAME
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.EMP_NAME
     *
     * @param empName the value for EMPLOYEE.EMP_NAME
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.EMP_NUM
     *
     * @return the value of EMPLOYEE.EMP_NUM
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public String getEmpNum() {
        return empNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.EMP_NUM
     *
     * @param empNum the value for EMPLOYEE.EMP_NUM
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setEmpNum(String empNum) {
        this.empNum = empNum == null ? null : empNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.PASSWORD
     *
     * @return the value of EMPLOYEE.PASSWORD
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.PASSWORD
     *
     * @param password the value for EMPLOYEE.PASSWORD
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.GENDER
     *
     * @return the value of EMPLOYEE.GENDER
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.GENDER
     *
     * @param gender the value for EMPLOYEE.GENDER
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.BIRTHDAY
     *
     * @return the value of EMPLOYEE.BIRTHDAY
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.BIRTHDAY
     *
     * @param birthday the value for EMPLOYEE.BIRTHDAY
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.DEPARTMENT_ID
     *
     * @return the value of EMPLOYEE.DEPARTMENT_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.DEPARTMENT_ID
     *
     * @param departmentId the value for EMPLOYEE.DEPARTMENT_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.POSITION_ID
     *
     * @return the value of EMPLOYEE.POSITION_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.POSITION_ID
     *
     * @param positionId the value for EMPLOYEE.POSITION_ID
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.PHONE
     *
     * @return the value of EMPLOYEE.PHONE
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.PHONE
     *
     * @param phone the value for EMPLOYEE.PHONE
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.EMAIL
     *
     * @return the value of EMPLOYEE.EMAIL
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.EMAIL
     *
     * @param email the value for EMPLOYEE.EMAIL
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.QQ
     *
     * @return the value of EMPLOYEE.QQ
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.QQ
     *
     * @param qq the value for EMPLOYEE.QQ
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.INTRODUCTION
     *
     * @return the value of EMPLOYEE.INTRODUCTION
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.INTRODUCTION
     *
     * @param introduction the value for EMPLOYEE.INTRODUCTION
     *
     * @mbggenerated Mon Jun 29 16:50:22 CST 2015
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}