package com.icss.oa.system.pojo;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.PERM_ID
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    private Integer permId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.PERM_NAME
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    private String permName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.PERM_INFO
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    private String permInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.PERM_ID
     *
     * @return the value of PERMISSION.PERM_ID
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    public Integer getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.PERM_ID
     *
     * @param permId the value for PERMISSION.PERM_ID
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    public void setPermId(Integer permId) {
        this.permId = permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.PERM_NAME
     *
     * @return the value of PERMISSION.PERM_NAME
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    public String getPermName() {
        return permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.PERM_NAME
     *
     * @param permName the value for PERMISSION.PERM_NAME
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    public void setPermName(String permName) {
        this.permName = permName == null ? null : permName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.PERM_INFO
     *
     * @return the value of PERMISSION.PERM_INFO
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    public String getPermInfo() {
        return permInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.PERM_INFO
     *
     * @param permInfo the value for PERMISSION.PERM_INFO
     *
     * @mbggenerated Tue Jun 30 09:17:11 CST 2015
     */
    public void setPermInfo(String permInfo) {
        this.permInfo = permInfo == null ? null : permInfo.trim();
    }
}