package com.icss.oa.system.pojo;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITION.POS_ID
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    private Integer posId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITION.POS_NAME
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    private String posName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSITION.POS_INFO
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    private String posInfo;

    public Position(Integer posId, String posName, String posInfo) {
		this.posId = posId;
		this.posName = posName;
		this.posInfo = posInfo;
	}

	public Position() {
	}

	public Position(String posName, String posInfo) {
		this.posName = posName;
		this.posInfo = posInfo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITION.POS_ID
     *
     * @return the value of POSITION.POS_ID
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    public Integer getPosId() {
        return posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITION.POS_ID
     *
     * @param posId the value for POSITION.POS_ID
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    public void setPosId(Integer posId) {
        this.posId = posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITION.POS_NAME
     *
     * @return the value of POSITION.POS_NAME
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    public String getPosName() {
        return posName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITION.POS_NAME
     *
     * @param posName the value for POSITION.POS_NAME
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    public void setPosName(String posName) {
        this.posName = posName == null ? null : posName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSITION.POS_INFO
     *
     * @return the value of POSITION.POS_INFO
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    public String getPosInfo() {
        return posInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSITION.POS_INFO
     *
     * @param posInfo the value for POSITION.POS_INFO
     *
     * @mbggenerated Tue Jun 30 08:35:36 CST 2015
     */
    public void setPosInfo(String posInfo) {
        this.posInfo = posInfo == null ? null : posInfo.trim();
    }
}