package com.icss.oa.card.pojo;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CARD_ID
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    private Integer cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CATA_ID
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    private Integer cataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CARD_NAME
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CARD_PHONE
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    private String cardPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CARD_POSITION
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    private String cardPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CARD_DEPT
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    private String cardDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CATA_NAME
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CARD_ID
     *
     * @param cardId the value for CARD.CARD_ID
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CATA_ID
     *
     * @return the value of CARD.CATA_ID
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public Integer getCataId() {
        return cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CATA_ID
     *
     * @param cataId the value for CARD.CATA_ID
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public void setCataId(Integer cataId) {
        this.cataId = cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CARD_NAME
     *
     * @return the value of CARD.CARD_NAME
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CARD_NAME
     *
     * @param cardName the value for CARD.CARD_NAME
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CARD_PHONE
     *
     * @return the value of CARD.CARD_PHONE
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public String getCardPhone() {
        return cardPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CARD_PHONE
     *
     * @param cardPhone the value for CARD.CARD_PHONE
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public void setCardPhone(String cardPhone) {
        this.cardPhone = cardPhone == null ? null : cardPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CARD_POSITION
     *
     * @return the value of CARD.CARD_POSITION
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public String getCardPosition() {
        return cardPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CARD_POSITION
     *
     * @param cardPosition the value for CARD.CARD_POSITION
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public void setCardPosition(String cardPosition) {
        this.cardPosition = cardPosition == null ? null : cardPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CARD_DEPT
     *
     * @return the value of CARD.CARD_DEPT
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public String getCardDept() {
        return cardDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CARD_DEPT
     *
     * @param cardDept the value for CARD.CARD_DEPT
     *
     * @mbggenerated Wed Jul 15 22:02:35 CST 2015
     */
    public void setCardDept(String cardDept) {
        this.cardDept = cardDept == null ? null : cardDept.trim();
    }

	public Card() {
		super();
	}

	public Card(Integer cataId, String cardName, String cardPhone,
			String cardPosition, String cardDept) {
		super();
		this.cataId = cataId;
		this.cardName = cardName;
		this.cardPhone = cardPhone;
		this.cardPosition = cardPosition;
		this.cardDept = cardDept;
	}

	public Card(Integer cardId, Integer cataId, String cardName,
			String cardPhone, String cardPosition, String cardDept) {
		super();
		this.cardId = cardId;
		this.cataId = cataId;
		this.cardName = cardName;
		this.cardPhone = cardPhone;
		this.cardPosition = cardPosition;
		this.cardDept = cardDept;
	}

}