package com.icss.oa.card.pojo;

public class CardCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_CATEGORY.CATA_ID
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    private Integer cataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_CATEGORY.EMP_ID
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_CATEGORY.CATA_NAME
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    private String cataName;

    /**
     * This field was generated by MyBatis Generator
     * This field corresponds to the database column CARD_CATEGORY.CAN_DELETE
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    private Integer canDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_CATEGORY.CATA_ID
     *
     * @return the value of CARD_CATEGORY.CATA_ID
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    
    public CardCategory(){
    	super();
    }
    
    public CardCategory(Integer empId,String cataName,Integer canDelete){
    	this.empId = empId;
    	this.cataName = cataName;
    	this.canDelete = canDelete;   	
    }
    
    public CardCategory(Integer cataId,Integer empId,String cataName,Integer canDelete){
    	this.cataId = cataId;
    	this.empId = empId;
    	this.cataName = cataName;
    	this.canDelete = canDelete;   	
    }
    
    public Integer getCataId() {
        return cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_CATEGORY.CATA_ID
     *
     * @param cataId the value for CARD_CATEGORY.CATA_ID
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    public void setCataId(Integer cataId) {
        this.cataId = cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_CATEGORY.EMP_ID
     *
     * @return the value of CARD_CATEGORY.EMP_ID
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_CATEGORY.EMP_ID
     *
     * @param empId the value for CARD_CATEGORY.EMP_ID
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_CATEGORY.CATA_NAME
     *
     * @return the value of CARD_CATEGORY.CATA_NAME
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    public String getCataName() {
        return cataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_CATEGORY.CATA_NAME
     *
     * @param cataName the value for CARD_CATEGORY.CATA_NAME
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    public void setCataName(String cataName) {
        this.cataName = cataName == null ? null : cataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_CATEGORY.CAN_DELETE
     *
     * @return the value of CARD_CATEGORY.CAN_DELETE
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    public Integer getCanDelete() {
        return canDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_CATEGORY.CAN_DELETE
     *
     * @param canDelete the value for CARD_CATEGORY.CAN_DELETE
     *
     * @mbggenerated Mon Jul 06 10:58:00 CST 2015
     */
    public void setCanDelete(Integer canDelete) {
        this.canDelete = canDelete;
    }
    
    @Override
	public String toString() {
		return "CardCategory [cataId=" + cataId + ", empId=" + empId + ", cataName=" + cataName
				+ ",canDelete= "+ canDelete +"]";
	} 
}