package com.icss.oa.room.pojo;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM.ROOM_ID
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM.ROOM_NAME
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM.ROOM_NUM
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    private String roomPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM.ROOM_STATE
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    private Short roomState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM.ACCOM_NUM
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    private Integer accomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM.AIR_CON
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    private Short airCon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM.ROOM_ID
     *
     * @return the value of ROOM.ROOM_ID
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM.ROOM_ID
     *
     * @param roomId the value for ROOM.ROOM_ID
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM.ROOM_NAME
     *
     * @return the value of ROOM.ROOM_NAME
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM.ROOM_NAME
     *
     * @param roomName the value for ROOM.ROOM_NAME
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM.ROOM_NUM
     *
     * @return the value of ROOM.ROOM_NUM
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public String getRoomPlace() {
        return roomPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM.ROOM_NUM
     *
     * @param roomNum the value for ROOM.ROOM_NUM
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public void setRoomPlace(String roomPlace) {
        this.roomPlace = roomPlace == null ? null : roomPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM.ROOM_STATE
     *
     * @return the value of ROOM.ROOM_STATE
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public Short getRoomState() {
        return roomState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM.ROOM_STATE
     *
     * @param roomState the value for ROOM.ROOM_STATE
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public void setRoomState(Short roomState) {
        this.roomState = roomState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM.ACCOM_NUM
     *
     * @return the value of ROOM.ACCOM_NUM
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public Integer getAccomNum() {
        return accomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM.ACCOM_NUM
     *
     * @param accomNum the value for ROOM.ACCOM_NUM
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public void setAccomNum(Integer accomNum) {
        this.accomNum = accomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM.AIR_CON
     *
     * @return the value of ROOM.AIR_CON
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public Short getAirCon() {
        return airCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM.AIR_CON
     *
     * @param airCon the value for ROOM.AIR_CON
     *
     * @mbggenerated Tue Jun 30 09:01:50 CST 2015
     */
    public void setAirCon(Short airCon) {
        this.airCon = airCon;
    }

	public Room(Integer roomId, String roomName, String roomPlace,
			Short roomState, Integer accomNum, Short airCon) {
		super();
		this.roomId = roomId;
		this.roomName = roomName;
		this.roomPlace = roomPlace;
		this.roomState = roomState;
		this.accomNum = accomNum;
		this.airCon = airCon;
	}

	public Room( String roomName, String roomPlace,
			Short roomState, Integer accomNum, Short airCon) {
		super();
		this.roomName = roomName;
		this.roomPlace = roomPlace;
		this.roomState = roomState;
		this.accomNum = accomNum;
		this.airCon = airCon;
	}


	public Room() {
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "Room [roomId=" + roomId + ", roomName=" + roomName
				+ ", roomPlace=" + roomPlace + ", roomState=" + roomState
				+ ", accomNum=" + accomNum + ", airCon=" + airCon + "]";
	}
    
    
    
    
    
}