package com.icss.oa.process.pojo;

import java.util.Date;

public class Reimbursement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.REIM_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private Integer reimId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.REIM_TIME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private Date reimTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.REIM_SUM
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private Double reimSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.EMP_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.REIM_REASON
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private String reimReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.LEADER_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private Integer leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.EMP_NAME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.LEADER_NAME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private String leaderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.STATUS
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REIMBURSEMENT.ENDSTATUS
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    private Integer endstatus;

    public Reimbursement() {
	}

	public Reimbursement(Integer reimId, Date reimTime, Double reimSum,
			Integer empId, String reimReason, Integer leaderId, String empName,
			String leaderName, Integer status, Integer endstatus) {
		this.reimId = reimId;
		this.reimTime = reimTime;
		this.reimSum = reimSum;
		this.empId = empId;
		this.reimReason = reimReason;
		this.leaderId = leaderId;
		this.empName = empName;
		this.leaderName = leaderName;
		this.status = status;
		this.endstatus = endstatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.REIM_ID
     *
     * @return the value of REIMBURSEMENT.REIM_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public Integer getReimId() {
        return reimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.REIM_ID
     *
     * @param reimId the value for REIMBURSEMENT.REIM_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setReimId(Integer reimId) {
        this.reimId = reimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.REIM_TIME
     *
     * @return the value of REIMBURSEMENT.REIM_TIME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public Date getReimTime() {
        return reimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.REIM_TIME
     *
     * @param reimTime the value for REIMBURSEMENT.REIM_TIME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setReimTime(Date reimTime) {
        this.reimTime = reimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.REIM_SUM
     *
     * @return the value of REIMBURSEMENT.REIM_SUM
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public Double getReimSum() {
        return reimSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.REIM_SUM
     *
     * @param reimSum the value for REIMBURSEMENT.REIM_SUM
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setReimSum(Double reimSum) {
        this.reimSum = reimSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.EMP_ID
     *
     * @return the value of REIMBURSEMENT.EMP_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.EMP_ID
     *
     * @param empId the value for REIMBURSEMENT.EMP_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.REIM_REASON
     *
     * @return the value of REIMBURSEMENT.REIM_REASON
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public String getReimReason() {
        return reimReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.REIM_REASON
     *
     * @param reimReason the value for REIMBURSEMENT.REIM_REASON
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setReimReason(String reimReason) {
        this.reimReason = reimReason == null ? null : reimReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.LEADER_ID
     *
     * @return the value of REIMBURSEMENT.LEADER_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public Integer getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.LEADER_ID
     *
     * @param leaderId the value for REIMBURSEMENT.LEADER_ID
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.EMP_NAME
     *
     * @return the value of REIMBURSEMENT.EMP_NAME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.EMP_NAME
     *
     * @param empName the value for REIMBURSEMENT.EMP_NAME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.LEADER_NAME
     *
     * @return the value of REIMBURSEMENT.LEADER_NAME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.LEADER_NAME
     *
     * @param leaderName the value for REIMBURSEMENT.LEADER_NAME
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName == null ? null : leaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.STATUS
     *
     * @return the value of REIMBURSEMENT.STATUS
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.STATUS
     *
     * @param status the value for REIMBURSEMENT.STATUS
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REIMBURSEMENT.ENDSTATUS
     *
     * @return the value of REIMBURSEMENT.ENDSTATUS
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public Integer getEndstatus() {
        return endstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REIMBURSEMENT.ENDSTATUS
     *
     * @param endstatus the value for REIMBURSEMENT.ENDSTATUS
     *
     * @mbggenerated Thu Jul 23 08:38:25 CST 2015
     */
    public void setEndstatus(Integer endstatus) {
        this.endstatus = endstatus;
    }

	@Override
	public String toString() {
		return "Reimbursement [reimId=" + reimId + ", reimTime=" + reimTime
				+ ", reimSum=" + reimSum + ", empId=" + empId + ", reimReason="
				+ reimReason + ", leaderId=" + leaderId + ", empName="
				+ empName + ", leaderName=" + leaderName + ", status=" + status
				+ ", endstatus=" + endstatus + "]";
	}
}