package com.icss.oa.emp_meeting.pojo;

public class EmpMeeting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP_MEETING.EM_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    private Integer emId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP_MEETING.EMP_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP_MEETING.MEET_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    private Integer meetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP_MEETING.EM_ID
     *
     * @return the value of EMP_MEETING.EM_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    public Integer getEmId() {
        return emId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP_MEETING.EM_ID
     *
     * @param emId the value for EMP_MEETING.EM_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    public void setEmId(Integer emId) {
        this.emId = emId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP_MEETING.EMP_ID
     *
     * @return the value of EMP_MEETING.EMP_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP_MEETING.EMP_ID
     *
     * @param empId the value for EMP_MEETING.EMP_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP_MEETING.MEET_ID
     *
     * @return the value of EMP_MEETING.MEET_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    public Integer getMeetId() {
        return meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP_MEETING.MEET_ID
     *
     * @param meetId the value for EMP_MEETING.MEET_ID
     *
     * @mbggenerated Mon Jul 20 08:41:26 CST 2015
     */
    public void setMeetId(Integer meetId) {
        this.meetId = meetId;
    }

	public EmpMeeting() {
		super();
		// TODO Auto-generated constructor stub
	}

	public EmpMeeting(Integer empId, Integer meetId) {
		super();
		this.empId = empId;
		this.meetId = meetId;
	}

	public EmpMeeting(Integer emId, Integer empId, Integer meetId) {
		super();
		this.emId = emId;
		this.empId = empId;
		this.meetId = meetId;
	}
    
}