package com.icss.oa.message.pojo;

import java.sql.Timestamp;

public class Message {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MESSAGE.MESSAGE_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	private Long messageId = (long) 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MESSAGE.SENDER_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	private Integer senderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MESSAGE.RECIPIENT_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	private Integer recipientId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MESSAGE.SEND_DATE
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	private Timestamp sendDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MESSAGE.SEND_STATUS
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	private Short sendStatus = 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MESSAGE.READ_STATUS
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	private Short readStatus = 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column MESSAGE.CONTENT
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	private String content;
	
	private String summary;

	public Message() {
		super();
	}

	public Message(Integer senderId, Integer recipientId, String content) {
		super();
		this.senderId = senderId;
		this.recipientId = recipientId;
		this.content = content;
		this.summary = this.createSummary();
	}

	public Message(Integer senderId, String content) {
		super();
		this.senderId = senderId;
		this.content = content;
		this.summary = this.createSummary();
	}

	public Message(Long messageId, Integer senderId, Integer recipientId,
			String content) {
		super();
		this.messageId = messageId;
		this.senderId = senderId;
		this.recipientId = recipientId;
		this.content = content;
		this.summary = this.createSummary();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MESSAGE.MESSAGE_ID
	 * 
	 * @return the value of MESSAGE.MESSAGE_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public Long getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MESSAGE.MESSAGE_ID
	 * 
	 * @param messageId
	 *            the value for MESSAGE.MESSAGE_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MESSAGE.SENDER_ID
	 * 
	 * @return the value of MESSAGE.SENDER_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public Integer getSenderId() {
		return senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MESSAGE.SENDER_ID
	 * 
	 * @param senderId
	 *            the value for MESSAGE.SENDER_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public void setSenderId(Integer senderId) {
		this.senderId = senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MESSAGE.RECIPIENT_ID
	 * 
	 * @return the value of MESSAGE.RECIPIENT_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public Integer getRecipientId() {
		return recipientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MESSAGE.RECIPIENT_ID
	 * 
	 * @param recipientId
	 *            the value for MESSAGE.RECIPIENT_ID
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public void setRecipientId(Integer recipientId) {
		this.recipientId = recipientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MESSAGE.SEND_DATE
	 * 
	 * @return the value of MESSAGE.SEND_DATE
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public Timestamp getSendDate() {
		return sendDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MESSAGE.SEND_DATE
	 * 
	 * @param sendDate
	 *            the value for MESSAGE.SEND_DATE
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public void setSendDate(Timestamp sendDate) {
		this.sendDate = sendDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MESSAGE.SEND_STATUS
	 * 
	 * @return the value of MESSAGE.SEND_STATUS
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public Short getSendStatus() {
		return sendStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MESSAGE.SEND_STATUS
	 * 
	 * @param sendStatus
	 *            the value for MESSAGE.SEND_STATUS
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public void setSendStatus(Short sendStatus) {
		this.sendStatus = sendStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MESSAGE.READ_STATUS
	 * 
	 * @return the value of MESSAGE.READ_STATUS
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public Short getReadStatus() {
		return readStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MESSAGE.READ_STATUS
	 * 
	 * @param readStatus
	 *            the value for MESSAGE.READ_STATUS
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public void setReadStatus(Short readStatus) {
		this.readStatus = readStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MESSAGE.CONTENT
	 * 
	 * @return the value of MESSAGE.CONTENT
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public String getContent() {
		return content;
	}

	public String createSummary() {
		int reInt = 0;//结果字符数
		String reStr = "";//结果字符串
		int toCount = 60;//截取字符数
		String more = "......";//附加符号
		if (content == null)
			return "";
		char[] tempChar = content.toCharArray();
		for (int kk = 0; (kk < tempChar.length && toCount > reInt); kk++) {
			if(tempChar[kk]=='<'){
				kk++;
				while(tempChar[kk]!='>'){
					kk++;
				}
				continue;
			}
			reInt ++;
			reStr += tempChar[kk];
		}
		if (toCount == reInt || (toCount == reInt - 1))
			reStr += more;
		return reStr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MESSAGE.CONTENT
	 * 
	 * @param content
	 *            the value for MESSAGE.CONTENT
	 * 
	 * @mbggenerated Tue Jun 30 09:44:26 CST 2015
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
		this.summary = this.createSummary();
	}

	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Override
	public String toString() {
		// SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		// String senddate = sdf.format(sendDate);
		return "Message [messageId=" + messageId + ", senderId=" + senderId
				+ ", recipientId=" + recipientId + ", sendDate=" + sendDate
				+ ", sendStatus=" + sendStatus + ", readStatus=" + readStatus
				+ ", content=" + content + "]";
	}

}