package com.icss.oa.assign.pojo;

public class AssignEmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.ASS_ID
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private Integer assId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.ASS_NAME
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private String assName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.EDUCATION
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.WORK_EXP
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private String workExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.SKILL
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private String skill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.RESIDENT_CITY
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private String residentCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.SALARY
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_EMP.RESUME
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private byte[] resume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGN_EMP.ASS_ID
     *
     * @return the value of ASSIGN_EMP.ASS_ID
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    private String available;
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGN_EMP.ASS_ID
     *
     * @return the value of ASSIGN_EMP.ASS_ID
     *
     * @mbggenerated Tue Jun 30 09:00:29 CST 2015
     */
    
    public AssignEmp() {
		super();
	}
    
    public AssignEmp(String available) {
		super();
		this.available = available;
	}

	public AssignEmp(Integer assId, String available) {
		super();
		this.assId = assId;
		this.available = available;
	}
    
    public AssignEmp(Integer assId, String assName, String education,
			String workExp, String skill, String residentCity, Integer salary,
			byte[] resume, String available) {
		super();
		this.assId = assId;
		this.assName = assName;
		this.education = education;
		this.workExp = workExp;
		this.skill = skill;
		this.residentCity = residentCity;
		this.salary = salary;
		this.resume = resume;
		this.available = available;
	}

	public AssignEmp(String assName, String education, String workExp,
			String skill, String residentCity, Integer salary, byte[] resume, String available) {
		super();
		this.assName = assName;
		this.education = education;
		this.workExp = workExp;
		this.skill = skill;
		this.residentCity = residentCity;
		this.salary = salary;
		this.resume = resume;
		this.available = available;
	}


	public AssignEmp(Integer assId, String assName, String education,
			String workExp, String skill, String residentCity, Integer salary,
			String available) {
		super();
		this.assId = assId;
		this.assName = assName;
		this.education = education;
		this.workExp = workExp;
		this.skill = skill;
		this.residentCity = residentCity;
		this.salary = salary;
		this.available = available;
	}

	public AssignEmp(String assName, String education, String workExp,
			String skill, String residentCity, Integer salary, String available) {
		super();
		this.assName = assName;
		this.education = education;
		this.workExp = workExp;
		this.skill = skill;
		this.residentCity = residentCity;
		this.salary = salary;
		this.available = available;
	}

	public Integer getAssId() {
        return assId;
    }

    public void setAssId(Integer assId) {
        this.assId = assId;
    }

    public String getAssName() {
        return assName;
    }

    public void setAssName(String assName) {
        this.assName = assName == null ? null : assName.trim();
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    public String getWorkExp() {
        return workExp;
    }

    public void setWorkExp(String workExp) {
        this.workExp = workExp == null ? null : workExp.trim();
    }

    public String getSkill() {
        return skill;
    }

    public void setSkill(String skill) {
        this.skill = skill == null ? null : skill.trim();
    }

    public String getResidentCity() {
        return residentCity;
    }

    public void setResidentCity(String residentCity) {
        this.residentCity = residentCity == null ? null : residentCity.trim();
    }

    public Integer getSalary() {
        return salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

	public byte[] getResume() {
		return resume;
	}

	public void setResume(byte[] resume) {
		this.resume = resume;
	}

	public String getAvailable() {
		return available;
	}

	public void setAvailable(String available) {
		this.available = available == null ? null : available.trim();
	}    
	

    @Override
	public String toString() {
		return "AssignEmp [assId=" + assId + ", assName=" + assName+ ", education=" + education + ", workExp=" + workExp
				+ "skill=" + skill + ", residentCity=" + residentCity + ", salary=" + salary + ", resume=" + resume + ", available=" + available + "]";
	}   
}