package com.icss.oa.assign.pojo;

public class AssignCom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_COM.ASS_COM_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private Integer assComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_COM.COM_NAME
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String comName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_COM.CONTACT_NAME
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_COM.CONTACT_PHONE
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_COM.CONTACT_QQ
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String contactQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSIGN_COM.REMARKS
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGN_COM.ASS_COM_ID
     *
     * @return the value of ASSIGN_COM.ASS_COM_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String posReq;
    
    private Integer comReqId;

    public Integer getComReqId() {
		return comReqId;
	}

	public void setComReqId(Integer comReqId) {
		this.comReqId = comReqId;
	}

	public String getPosReq() {
		return posReq;
	}

	public void setPosReq(String posReq) {
		this.posReq = posReq;
	}

	public String getTypeOfWork() {
		return typeOfWork;
	}

	public void setTypeOfWork(String typeOfWork) {
		this.typeOfWork = typeOfWork;
	}

	public String getSalaryPermonth() {
		return salaryPermonth;
	}

	public void setSalaryPermonth(String salaryPermonth) {
		this.salaryPermonth = salaryPermonth;
	}
	

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COM_REQ.TYPE_OF_WORK
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String typeOfWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COM_REQ.SALARY_PERMONTH
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String salaryPermonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COM_REQ.COM_REQ_ID
     *
     * @return the value of COM_REQ.COM_REQ_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */

    public AssignCom() {
		super();
	}

	

	public AssignCom(String comName, String contactName, String contactPhone,
			String contactQq, String remarks, String posReq, Integer comReqId,
			String typeOfWork, String salaryPermonth) {
		super();
		this.comName = comName;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.contactQq = contactQq;
		this.remarks = remarks;
		this.posReq = posReq;
		this.comReqId = comReqId;
		this.typeOfWork = typeOfWork;
		this.salaryPermonth = salaryPermonth;
	}

	public AssignCom(Integer assComId, String comName, String contactName,
			String contactPhone, String contactQq, String remarks,
			String posReq, Integer comReqId, String typeOfWork,
			String salaryPermonth) {
		super();
		this.assComId = assComId;
		this.comName = comName;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.contactQq = contactQq;
		this.remarks = remarks;
		this.posReq = posReq;
		this.comReqId = comReqId;
		this.typeOfWork = typeOfWork;
		this.salaryPermonth = salaryPermonth;
	}

	public AssignCom(Integer assComId, String comName, String contactName,
			String contactPhone, String contactQq, String remarks) {
		super();
		this.assComId = assComId;
		this.comName = comName;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.contactQq = contactQq;
		this.remarks = remarks;
	}


	public AssignCom(String comName, String contactName, String contactPhone,
			String contactQq, String remarks) {
		super();
		this.comName = comName;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.contactQq = contactQq;
		this.remarks = remarks;
	}

	
	
    public Integer getAssComId() {
        return assComId;
    }

    public void setAssComId(Integer assComId) {
		this.assComId = assComId;
	}

    public String getComName() {
        return comName;
    }

    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGN_COM.CONTACT_NAME
     *
     * @return the value of ASSIGN_COM.CONTACT_NAME
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGN_COM.CONTACT_NAME
     *
     * @param contactName the value for ASSIGN_COM.CONTACT_NAME
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGN_COM.CONTACT_PHONE
     *
     * @return the value of ASSIGN_COM.CONTACT_PHONE
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGN_COM.CONTACT_PHONE
     *
     * @param contactPhone the value for ASSIGN_COM.CONTACT_PHONE
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGN_COM.CONTACT_QQ
     *
     * @return the value of ASSIGN_COM.CONTACT_QQ
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public String getContactQq() {
        return contactQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGN_COM.CONTACT_QQ
     *
     * @param contactQq the value for ASSIGN_COM.CONTACT_QQ
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setContactQq(String contactQq) {
        this.contactQq = contactQq == null ? null : contactQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSIGN_COM.REMARKS
     *
     * @return the value of ASSIGN_COM.REMARKS
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSIGN_COM.REMARKS
     *
     * @param remarks the value for ASSIGN_COM.REMARKS
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	@Override
	public String toString() {
		return "AssignCom [assComId=" + assComId + ", comName=" + comName
				+ ", contactName=" + contactName + ", contactPhone="
				+ contactPhone + ", contactQq=" + contactQq + ", remarks="
				+ remarks + "]";
	}
    
}