package com.icss.oa.assign.pojo;

public class ComReq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COM_REQ.COM_REQ_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private Integer comReqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COM_REQ.ASS_COM_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private Integer assComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COM_REQ.POS_REQ
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String posReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COM_REQ.TYPE_OF_WORK
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String typeOfWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COM_REQ.SALARY_PERMONTH
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String salaryPermonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COM_REQ.COM_REQ_ID
     *
     * @return the value of COM_REQ.COM_REQ_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    private String comName; 
    
    
    public ComReq(Integer comReqId, Integer assComId, String posReq,
			String typeOfWork, String salaryPermonth, String comName) {
		super();
		this.comReqId = comReqId;
		this.assComId = assComId;
		this.posReq = posReq;
		this.typeOfWork = typeOfWork;
		this.salaryPermonth = salaryPermonth;
		this.comName = comName;
	}

	public ComReq(Integer assComId, String posReq, String typeOfWork,
			String salaryPermonth, String comName) {
		super();
		this.assComId = assComId;
		this.posReq = posReq;
		this.typeOfWork = typeOfWork;
		this.salaryPermonth = salaryPermonth;
		this.comName = comName;
	}

	public Integer getComReqId() {
        return comReqId;
    }

	public ComReq(Integer assComId, String posReq, String typeOfWork,
			String salaryPermonth) {
		super();
		this.assComId = assComId;
		this.posReq = posReq;
		this.typeOfWork = typeOfWork;
		this.salaryPermonth = salaryPermonth;
	}

	public ComReq() {
		super();
	}

	public ComReq(Integer comReqId, Integer assComId, String posReq,
			String typeOfWork, String salaryPermonth) {
		super();
		this.comReqId = comReqId;
		this.assComId = assComId;
		this.posReq = posReq;
		this.typeOfWork = typeOfWork;
		this.salaryPermonth = salaryPermonth;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COM_REQ.COM_REQ_ID
     *
     * @param comReqId the value for COM_REQ.COM_REQ_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setComReqId(Integer comReqId) {
        this.comReqId = comReqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COM_REQ.ASS_COM_ID
     *
     * @return the value of COM_REQ.ASS_COM_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public Integer getAssComId() {
        return assComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COM_REQ.ASS_COM_ID
     *
     * @param assComId the value for COM_REQ.ASS_COM_ID
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setAssComId(Integer assComId) {
        this.assComId = assComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COM_REQ.POS_REQ
     *
     * @return the value of COM_REQ.POS_REQ
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public String getPosReq() {
        return posReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COM_REQ.POS_REQ
     *
     * @param posReq the value for COM_REQ.POS_REQ
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setPosReq(String posReq) {
        this.posReq = posReq == null ? null : posReq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COM_REQ.TYPE_OF_WORK
     *
     * @return the value of COM_REQ.TYPE_OF_WORK
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public String getTypeOfWork() {
        return typeOfWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COM_REQ.TYPE_OF_WORK
     *
     * @param typeOfWork the value for COM_REQ.TYPE_OF_WORK
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setTypeOfWork(String typeOfWork) {
        this.typeOfWork = typeOfWork == null ? null : typeOfWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COM_REQ.SALARY_PERMONTH
     *
     * @return the value of COM_REQ.SALARY_PERMONTH
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public String getSalaryPermonth() {
        return salaryPermonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COM_REQ.SALARY_PERMONTH
     *
     * @param salaryPermonth the value for COM_REQ.SALARY_PERMONTH
     *
     * @mbggenerated Wed Jul 08 14:59:41 CST 2015
     */
    public void setSalaryPermonth(String salaryPermonth) {
        this.salaryPermonth = salaryPermonth == null ? null : salaryPermonth.trim();
    }

	public String getComName() {
		return comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}
	
	@Override
	public String toString() {
		return "ComReq [comReqId=" + comReqId + ", assComId=" + assComId
				+ ", posReq=" + posReq + ", typeOfWork=" + typeOfWork
				+ ", salaryPermonth=" + salaryPermonth + ", comName=" + comName
				+ "]";
	}

	
}